extism/js-pdk

- README.md
wget isn't installed by default on macOS.  Update the script to use curl instead.
> Use curl instead of wget on macOS and fix Linux install instructions

- README.md
* Provide some prerequisite info on how to set up the toolchain for building the SDK
* Fix quotes in `"Hello World Test!"` which was causing an issue in zsh in MacOS related to the `!` being treated as a special character.
* Switch the script that's passed to the build example to use the `bundle.js` instead of `script.js`, which isn't buildable since it's not in cjs format.
Issue caused by the `!` (unterminated quote denoted by the `dquote>` prompt)
```
➜  js-pdk git:(main) ✗ extism call out.wasm count_vowels --wasi --input="Hello World Test!"
dquote> 
➜  js-pdk git:(main) ✗ extism call out.wasm count_vowels --wasi --input='Hello World Test!'
{"count":4}% ```
> Update readme to provide more context on compilation from source

- .github/workflows/ci.yml
- crates/core/Cargo.toml
- crates/core/src/globals.rs
- crates/core/src/lib.rs
Seems the sha specifier wasn't working. this backports some of the code to where it should be. I will have a follow up PR to upgrade to the new quickjs-wasm-rs API. Also need to add some CI but can't run / test it until it's merged.
> Fix dependency, backport code, add CI

- README.md
Would prefer to keep someone within the Extism realm, and then they can dig into AssemblyScript after seeing that we have a PDK for it.
> chore: link to the as-pdk rather than assemblyscript.org directly

- Cargo.toml
- crates/core/src/globals.rs
- examples/simple_js/script.js
- install.sh
Fixes #36 
Had some misunderstandings of the quickjs interface in rust in this code. This fixes the problem. However I think a longer term fix would be to move more of this code up into the polyfill / prelude area: https://github.com/extism/js-pdk/tree/main/crates/core/src/prelude
The reason being that more of our validation and preparation logic should be written in JS rather than rust because it's more ergonomic and the error messages are better.
> fix: Fixes HTTP Call code

- install.sh
`$OSTYPE` didn't work on my linux, so I just figured since already use `uname` in the script, we can double-dip.
> fix: use uname for os detection

- install.sh
I had an issue with building a plugin because `binaryen` wasn't installed/in my path. I mentioned on discord that having the install include `binaryen` be a good idea.
Looking for feedback on this.
Didn't find a contribution guide, apologies if I have missed steps in the process.
> add download and install of binaryen bin files to install script

- crates/core/src/globals.rs
When using the HTTP Client API from a JS plugin like this:
```javascript
const task = {
"userId":1, 
"id":2345,
"title":"title",
"completed":false
};
const request = {
method: "POST",
url: "https://jsonplaceholder.typicode.com/todos",
headers: {
"Accept": "application/json",
"Content-Type": "application/json",
},
};
const response = Http.request(
request, 
JSON.stringify(task),
);
```
it appears that the headers were never sent, hence the target server not being able to parse the body correctly and creating an empty task.
This pull request fix this behavior
> HTTP headers are never sent with the HTTP Client API

- .gitignore
- Cargo.toml
- crates/cli/Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/globals.rs
- crates/core/src/prelude/src/index.js
Closes #51
The caveat is that the JS code doesn't know anything about your timezone yet. It would probably be more efficient to pass an epoch timestamp than a string from the rust code. But i'm not sure how to create a number larger than 32 bits from the rust code at the moment.
> feat: Add basic support for Date

- README.md
- crates/cli/src/ts_parser.rs
- Returns an error when host  functions have more than 5 params 
- Updates limitations in README
> cleanup: include checks when parsing d.ts files to error when functions have the wrong number of parameters

- install.sh
Since https://github.com/extism/js-pdk/commit/fb8bf0442c594294d76a15c19dd2057d65ed200f only `wasm-merge` was actually installed.
This fixes the install script to install `wasm-opt` and in theory should work on partial/failed installations.
> fix: actually install wasm-opt

- install.sh
Installing wasm-merge this way doesn't seem to work on mac because binaryen is dynamically linked. So we will use homebrew instead.
> fix: use homebrew to install wasm-merge on mac

- crates/core/src/globals.rs
Some SDKs, like the js-sdk, store block index information in the top 16 bits of the 64-bit memory address. This is incompatible with the JS-PDK at present, since we truncate addresses to 32 bits. In advance of BigInt support in Javy/quickjs-wasm-sys, expose memory offset and lengths as JS Float values. This leans on the JS convention of storing (up to 53 bits of) integer data losslessly in an f64.
This gives us 5 bits of block index for the JS-SDK, enough room for *slaps roof of memory allocator* 32 allocations in this bad boy (before requiring an extism memory reset.)
QuickJS itself supports bigint, so it's a matter of looping that functionality out through quickjs-sys. (I haven't been able to find a technical reason this wasn't done initially, though that doesn't mean there aren't …
> fix: partial workaround for high address support

- crates/core/src/lib.rs
Sometimes when using bundlers to bundle the code for the plugin, bundlers would rename
the function before exporting it, so if you had something like:
```js
function myFunction() {
Host.outputString('Hello');
}
module.exports = { myFunction };
```
It could turn into something like:
```js
function myFunction2() {
Host.outputString('Hello');
}
module.exports = { myFunction: myFunction2 };
```
This would make it so that once the PDK invoked the function it would still try calling the 
`myFunction()` on the global context, which would end up calling another function except
for the one exported.
This PR fixes that by finding the export name inside `module.exports` instead of
the `global`.
> fix: plugin functions being accessed from global instead of from `module.exports`

- crates/core/src/globals.rs
Noticed `console.debug` was missing, so figured I'd add it. It's also not obvious what log level `console.log` has, so I added `console.info` as well as an alias, which seems to match browser behaviour. 
Diff looks a bit confusing, as I sorted the functions based on log level. 🤷
> feat: add info and debug logging to console global

- crates/core/src/prelude/src/http.ts
Rather than marking this required, check if its undefined and set to "GET" by default.
> fix: default to GET for http req method

- crates/core/src/prelude/esbuild.js
I ran into a headscratcher where my plugin worked without esbuild minification, but not when it was enabled. It would crash hard complaining something wasn't a function and sometimes it wasn't a constructor instead.
After some hours of debugging, it turns out the minification would cause a minified runtime global variable to be redeclared, so when the runtime tried to use its variable it would explode. Note while I say global, I mean all the variables meant to be locally scoped as well, as when the format is cjs, esbuild assume the code will run in its own scope so it won't isolate top-level variables. 
It isn't guaranteed to always cause issues, as usually shadowing a variable isn't a problem, but I'm guessing function hoisting complicated it in my case.
There should be no downside to …
> Change prelude format to iife

- crates/core/src/globals.rs
This PR fixes a couple of incompatibilities between the console.debug/log/warn/error statements.  `console.log("a", "b", "c");` in the exits js-pdk does not output the expected `a b c` but just outputs `a`.  also, an empty console.log errors out, but it normally is a no-op.
```
console.debug();
console.debug("debug: single console statement");
console.debug("debug:", "multiple", "console", "statements");
console.log();
console.log("log: single console statement");
console.log("log:", "multiple", "console", "statements");
console.warn();
console.warn("warn: single console statement");
console.warn("warn:", "multiple", "console", "statements");
console.error();
console.error("error: single console statement");
console.error("error:", "multiple", "console", "statements");
```
```
2024/05/26 …
```
> Update console.log implementation to support multiple params

- .github/workflows/ci.yml
- .github/workflows/ci_install.yml
- .github/workflows/publish.yml
- Makefile
- README.md
- examples/bundled/package-lock.json
- examples/bundled/package.json
- examples/kitchen-sink/package-lock.json
- examples/kitchen-sink/package.json
- examples/react/package-lock.json
- examples/react/package.json
- install-wasi-sdk.ps1
- install-windows.ps1
Closes #25 
This PR enable windows support for js-pdk cli.
The approach is minimalist and use line-by-line translation for the existing configs/code to facilitate the change validation. This have an impact on performance in some case (Test CI for windows) takes ~15min, some rework would be need to reduce the build time but I hope this would be fine for now. 
As discussed in [discord](https://discord.com/channels/1011124058408112148/1062468347851178165/1242975938116063302), wasm-opt v117 seems to have a [bug](https://github.com/WebAssembly/binaryen/issues/6639). 
In order to avoid running into it :
- In CI release worker, make sure js_pdk_core.wasm is optimized before packing it in the released binaries. *(1)
- In manual build process (Makefile), make sure js_pdk_core.wasm is optimized …
> feat(release): add windows cli release workflow

- .github/workflows/ci_install.yml
- README.md
- install-windows.ps1
The old version attempts to append Path during the install script. The result is flaky and doesn't work reliably : 
- Doesn't seem to persist value in local settings.
- Depending on the console type (cmd or powershell), the result is different
- CI vs local whole machine vs User profile ...
This fix removes the auto append and updates install instructions to leave the option to the user.
> fix(windows): install script, ci test install and documentation

- crates/core/src/globals.rs
- crates/core/src/prelude/src/memory.ts
Realizing that there are some places where having control of the behavior when a zero-offset memory handle would otherwise cause a panic/throw. This gives the caller control of how to interpret the result. 
For example, in the case of an `xtp-test-js` call output, I need to know that a call does not return any value.
> chore: modify mem find to return js undefined

- .github/workflows/ci_install.yml
- install.sh
This improves the extism-js install experience a bit:
* removes the hard coded TAG variable and fetches the latest tag from github api
* tries to install extism-js in a local bin before it asks for sudo and tries a system directory
* is a little more chatty about what it's doing and tells you when it's done and how to verify
> Better install script

- README.md
- crates/cli/src/main.rs
- crates/cli/src/options.rs
Pretty small change but makes the compilation faster if you want a faster iteration cycle. 
Without skip-opt:
```
[I] ben@dylibso ~/d/js-pdk (main)> time ./target/release/extism-js examples/simple_js/script.js -i examples/simple_js/script.d.ts -o examples/simple_js.wasm
[2024-10-16T15:48:41Z INFO  extism_js] parsed interface: 298.5µs
[2024-10-16T15:48:41Z INFO  extism_js] read user code: 38.417µs
[2024-10-16T15:48:41Z INFO  extism_js] concated user code: 3.209µs
[2024-10-16T15:48:41Z INFO  extism_js] command done: 60.358042ms
[2024-10-16T15:48:41Z INFO  extism_js] generated shims: 267.958µs
[2024-10-16T15:48:41Z INFO  extism_js] wasm merge check: 22.89325ms
[2024-10-16T15:48:41Z INFO  extism_js] wasm merge: 125.382209ms
[2024-10-16T15:48:42Z INFO  extism_js] wasm opt: 774.119041ms …
```
> Add flag to skip optimization

- crates/core/Cargo.toml
- crates/core/src/globals.rs
- crates/core/src/lib.rs
Resolves #87 by replacing quickjs-wasm-rs with rquickjs
---
Note: I'm working on this slowly but wanted to raise this draft PR for visibility and per [my reply here](https://github.com/extism/js-pdk/issues/87#issuecomment-2168762213)
> feat: migrate to rquickjs from quickjs-wasm-rs

- Makefile
Looks like this is passing now
> fix: enable tests with python host

- .github/workflows/ci.yml
- .github/workflows/ci_install.yml
- .github/workflows/publish.yml
- install.sh
- update the install script so that we can specify a tag
- pin the build runners to ubuntu-22.04 to make sure it doesn't need newer glibc versions:
```
❯ extism-js --version
extism-js: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.39' not found (required by extism-js)
```
This error is on my machine which is on ubuntu 22.04
> fix: pin ubuntu and update install script

- Makefile
- crates/core/src/globals.rs
- examples/base64/jsconfig.json
- examples/base64/script.d.ts
- examples/base64/script.js
- examples/kitchen-sink/package-lock.json
- examples/kitchen-sink/src/index.ts
> fix: correct ArrayBuffer validation in `arrayBufferToBase64`

- Makefile
- crates/core/src/globals.rs
- crates/core/src/prelude/src/console.ts
- crates/core/src/prelude/src/index.ts
- examples/console/jsconfig.json
- examples/console/script.d.ts
- examples/console/script.js
> fix: implement console in TS

- Cargo.toml
Sorry for the noise - going to release 1.5.0 instead. I forgot about https://github.com/extism/js-pdk/pull/125
> chore: update version to 1.5.0
